name: Docker Deploy

on:
  push:
    branches:
      - deploy  # 只在 deploy 分支触发
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/next-blog:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/next-blog:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/next-blog:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/next-blog:buildcache,mode=max